=== huliqing/LuoYing/ly-editor/data/template/LuoYing-RPG/editor/converter/meta.xsd
<?xml version="1.0"?>
<!--
    转换器定义
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://editor.huliqing.name"
           xmlns="http://editor.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="data" />
                <xs:element ref="converter" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="converter">
        <xs:annotation>
            <xs:documentation>定义一个转换器</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换器名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换器, 格式：name.huliqing.editor.converter.XXXConverter</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="feature">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>feature名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>feature值</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="data">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换tag名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="extends" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>继承自另一个转换器</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="converter" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>关联一个转换器定义</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="features" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>数据转换器的配置，格式："feature1,feature2,feature3"，如果不设置这个参数则使用关联的转换器的默认的配置</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
                <xs:element ref="field" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="field">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>指定要转换的字段名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="displayName" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>指定要显示的字段名称，如果没有指定则直接使用name属性的值作为显示名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="converter" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>关联一个转换器定义</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="base" >
    </xs:complexType>

</xs:schema>

=== huliqing/LuoYing/ly-editor/data/converter/base.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <!--DataConverters-->
    <converter name="SimpleDataConverter" value="name.huliqing.editor.converter.data.SimpleDataConverter" />
    
    <!--FieldConverters-->
    <converter name="CheckBoxConverter" value="name.huliqing.editor.converter.field.CheckBoxConverter" />
    <converter name="ChoiceConverter" value="name.huliqing.editor.converter.field.ChoiceConverter" />
    <converter name="ColorConverter" value="name.huliqing.editor.converter.field.ColorConverter" />
    <converter name="DataFieldConverter" value="name.huliqing.editor.converter.field.DataFieldConverter" />
    <converter name="FileConverter" value="name.huliqing.editor.converter.field.FileConverter" />
    <converter name="QuaternionConverter" value="name.huliqing.editor.converter.field.QuaternionConverter" />
    <converter name="TextConverter" value="name.huliqing.editor.converter.field.TextConverter" />
    <converter name="Vector2fConverter" value="name.huliqing.editor.converter.field.Vector2fConverter" />
    <converter name="Vector3fConverter" value="name.huliqing.editor.converter.field.Vector3fConverter" />
    <converter name="Vector4fConverter" value="name.huliqing.editor.converter.field.Vector4fConverter" />
    
    <data name="base" extends="" converter="SimpleDataConverter">
        <field name="id" converter="TextConverter">
            <feature name="disabled" value="true" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="extends" converter="TextConverter">
            <feature name="disabled" value="true" />
            <feature name="collapsed" value="true" />
        </field>
    </data>

    <data name="sound" extends="base" >
        <field name="file" converter="FileConverter" />
        <field name="type" converter="ChoiceConverter" >
            <feature name="items" value="Buffer,Stream" />
        </field>
        <field name="direction" converter="Vector3fConverter" />
        <field name="directional" converter="CheckBoxConverter" />
        <field name="positional" converter="CheckBoxConverter" />
        <field name="innerAngle" converter="TextConverter" />
        <field name="outerAngle" converter="TextConverter" />
        <field name="looping" converter="CheckBoxConverter" />
        <field name="maxDistance" converter="TextConverter" />
        <field name="pitch" converter="TextConverter" />
        <field name="refDistance" converter="TextConverter" />
        <field name="reverbEnabled" converter="CheckBoxConverter" />
        <field name="timeOffset" converter="TextConverter" />
        <field name="velocity" converter="Vector3fConverter" />
        <field name="velocityFromTranslation" converter="CheckBoxConverter" />
        <field name="volume" converter="TextConverter" />
    </data>
    
</root>

=== huliqing/LuoYing/ly-editor/data/template/LuoYing-RPG/editor/converter/drop.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="dropBase" extends="base">
        <field name="sounds" converter="ListDataFieldConverter" />
    </data>

    <data name="dropAttribute" extends="dropBase">
        <field name="attribute" converter="TextConverter" />
        <field name="valueHitEl" converter="TextConverter" />
    </data>

    <data name="dropGroup" extends="dropBase">
        <field name="drops" converter="TextConverter" />
    </data>

    <data name="dropItem" extends="dropBase">
        <field name="item" converter="TextConverter" />
        <field name="count" converter="IntegerTextConverter" />
        <field name="rate" converter="FloatTextConverter" />
    </data>

    <data name="dropSkin" extends="dropBase">
        <field name="skin" converter="TextConverter" />
        <field name="count" converter="IntegerTextConverter" />
        <field name="rate" converter="FloatTextConverter" />
    </data>
    
</root>

=== huliqing/LuoYing/ly-editor/data/template/LuoYing-RPG/editor/converter/bullet.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="bulletBase" extends="entityModelBase">
        <field name="debug" converter="CheckBoxConverter" />
        <field name="shape" converter="TextConverter" />
        <field name="shapeOffset" converter="Vector3fConverter" />
        <field name="timeout" converter="FloatTextConverter" />
        <field name="effects" converter="ListDataFieldConverter" />
        <field name="hitEffects" converter="ListDataFieldConverter" />
        <field name="sounds" converter="ListDataFieldConverter" />
        <field name="hitSounds" converter="ListDataFieldConverter" />
    </data>
    
    <data name="bulletPathBase" extends="bulletBase">
        <field name="baseSpeed" converter="FloatTextConverter" />
        <field name="facing" converter="CheckBoxConverter" />
        <field name="trace" converter="CheckBoxConverter" />
    </data>
    
    <data name="bulletCurveBase" extends="bulletPathBase">
        <field name="tension" converter="FloatTextConverter" />
        <field name="positions" converter="ListDataFieldConverter" />
        <field name="up" converter="Vector3fConverter" />
    </data>

    <data name="bulletSimple" extends="bulletBase" />

    <data name="bulletStraight" extends="bulletPathBase"/>

    <data name="bulletCurve" extends="bulletCurveBase"/>

    <data name="bulletCurveTrail" extends="bulletCurveBase">
        <field name="mask" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="tex" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="texScale" converter="FloatTextConverter" />
        <field name="color" converter="ColorConverter" />
        <field name="width" converter="FloatTextConverter" />
        <field name="dimension" converter="IntegerTextConverter" />
        <field name="segments" converter="IntegerTextConverter" />
    </data>
    
</root>

=== huliqing/LuoYing/ly-editor/data/template/LuoYing-RPG/editor/converter/effect.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="effectBase" extends="base" >
        <field name="useTime" converter="FloatTextConverter" />
        <field name="speed" converter="FloatTextConverter" />
        <field name="loop" converter="CheckBoxConverter" />
        <field name="animations" converter="TextConverter" />
        <field name="sounds" converter="TextConverter" />
        <field name="endImmediate" converter="CheckBoxConverter" />
        <field name="location" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="rotation" converter="QuaternionConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="scale" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="shadowMode" converter="ChoiceConverter">
            <feature name="items" value="Off,Cast,Receive,CastAndReceive,Inherit" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="cullHint" converter="ChoiceConverter">
            <feature name="items" value="Inherit,Dynamic,Always,Never" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="queueBucket" converter="ChoiceConverter">
            <feature name="items" value="Opaque,Transparent,Sky,Translucent,Gui,Inherit" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="traceLocation" converter="ChoiceConverter" >
            <feature name="items" value="no,once,always" />
        </field>
        <field name="traceRotation" converter="ChoiceConverter" >
            <feature name="items" value="no,once,always" />
        </field>
        <field name="traceLocationType" converter="ChoiceConverter" >
            <feature name="items" value="origin,origin_bound_center,origin_bound_top,bound_center,bound_top" />
        </field>
        <field name="traceLocationOffset" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="traceRotationOffset" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
    </data>
    
    <data name="effectGroup" extends="effectBase">
        <field name="effects" converter="TextConverter" />
    </data>
    
    <data name="effectParticle" extends="effectBase">
        <!--<field name="emitter" converter="TextConverter" />-->
        <field name="emitter" converter="DataFieldConverter" />
        <field name="emitAll" converter="CheckBoxConverter" />
        <field name="randomColor" converter="CheckBoxConverter" />
        <field name="inWorldSpace" converter="CheckBoxConverter" />
        <field name="blendMode" converter="ChoiceConverter" >
            <feature name="items" value="Alpha,AlphaAdditive" />
        </field>
    </data>
    
    <data name="effectTexture" extends="effectBase">
        <field name="texture" converter="TextConverter" />
        <field name="size" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="plane" converter="ChoiceConverter" >
            <feature name="items" value="xy,xz,yz" />
        </field>
        <field name="color" converter="ColorConverter" />
    </data>
    
    <data name="effectModel" extends="effectBase">
        <field name="file" converter="FileConverter">
            <feature name="filters" value="Model Files|*.j3o,All Files|*.*" />
        </field>
    </data>
    
    <data name="effectSlideColorBase" extends="effectBase">
        <field name="startColor" converter="ColorConverter" />
        <field name="endColor" converter="ColorConverter" />
        <field name="mask" converter="FileConverter">
            <feature name="filters" value="Model Files|*.jpg|*.png|*.bmp,All Files|*.*" />
        </field>
        <field name="maskAnimY" converter="CheckBoxConverter" />
        <field name="maskAnimX" converter="CheckBoxConverter" />
        <field name="maskChangeDir" converter="CheckBoxConverter" />
        <field name="maskScaleY" converter="FloatTextConverter" />
        <field name="maskScaleX" converter="FloatTextConverter" />
        <field name="maskSpeed" converter="FloatTextConverter" />
        <field name="maskWrap" converter="ChoiceConverter">
            <feature name="items" value="Repeat,MirroredRepeat" />
        </field>
        <field name="tex" converter="FileConverter">
            <feature name="filters" value="Model Files|*.jpg|*.png|*.bmp,All Files|*.*" />
        </field>
        <field name="texAnimY" converter="CheckBoxConverter" />
        <field name="texAnimX" converter="CheckBoxConverter" />
        <field name="texChangeDir" converter="CheckBoxConverter" />
        <field name="texScaleY" converter="FloatTextConverter" />
        <field name="texScaleX" converter="FloatTextConverter" />
        <field name="texSpeed" converter="FloatTextConverter" />
        <field name="texWrap" converter="ChoiceConverter">
            <feature name="items" value="Repeat,MirroredRepeat" />
        </field>
    </data>
    
    <data name="effectSlideColor" extends="effectSlideColorBase">
    </data>
    
    <data name="effectSlideColorSpline" extends="effectSlideColorBase">
        <field name="fixedPoints" converter="TextConverter" />
        <field name="randomPoints" converter="TextConverter" />
        <field name="width" converter="FloatTextConverter" />
        <field name="segments" converter="IntegerConverter" />
        <field name="tension" converter="FloatTextConverter" />
        <field name="cycle" converter="CheckBoxConverter" />
        <field name="up" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="dimension" converter="IntegerConverter" />
    </data>
    
    <data name="effectSlideColorIOSpline" extends="effectBase">
        <field name="startColor" converter="ColorConverter" />
        <field name="endColor" converter="ColorConverter" />
        <field name="mask" converter="FileConverter">
            <feature name="filters" value="Model Files|*.jpg|*.png|*.bmp,All Files|*.*" />
        </field>
        <field name="tex" converter="FileConverter">
            <feature name="filters" value="Model Files|*.jpg|*.png|*.bmp,All Files|*.*" />
        </field>
        <field name="texChangeDir" converter="CheckBoxConverter" />
        <field name="fixedPoints" converter="TextConverter" />
        <field name="randomPoints" converter="TextConverter" />
        <field name="width" converter="FloatTextConverter" />
        <field name="segments" converter="IntegerConverter" />
        <field name="tension" converter="FloatTextConverter" />
        <field name="cycle" converter="CheckBoxConverter" />
        <field name="up" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="dimension" converter="IntegerConverter" />
        <field name="repeatTimes" converter="IntegerConverter" />
    </data>
    
    <data name="effectProjection" extends="effectBase">
        <field name="texture" converter="FileConverter">
            <feature name="filters" value="Model Files|*.jpg|*.png|*.bmp,All Files|*.*" />
        </field>
        <field name="color" converter="ColorConverter" />
        <field name="projDir" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="projUp" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="projPos" converter="Vector3fConverter">
            <feature name="collapsed" value="true" />
        </field>
        <field name="debug" converter="CheckBoxConverter" />
    </data>

</root>

=== huliqing/LuoYing/ly-editor/data/template/LuoYing-RPG/editor/converter/emitter.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="emitterBase" extends="base">
    </data>

    <data name="emitter" extends="emitterBase">
        <field name="numParticles" converter="IntegerTextConverter" />
        <field name="startColor" converter="ColorConverter" />
        <field name="endColor" converter="ColorConverter" />
        <field name="startSize" converter="FloatTextConverter" />
        <field name="endSize" converter="FloatTextConverter" />
        <field name="highLife" converter="FloatTextConverter" />
        <field name="lowLife" converter="FloatTextConverter" />
        <field name="texture" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="imagesX" converter="IntegerTextConverter" />
        <field name="imagesY" converter="IntegerTextConverter" />
        <field name="gravity" converter="Vector3fConverter" />
        <field name="initialVelocity" converter="Vector3fConverter" />
        <field name="velocityVariation" converter="FloatTextConverter" />
        <field name="particlesPerSec" converter="IntegerTextConverter" />
        <field name="randomAngle" converter="CheckBoxConverter" />
        <field name="rotateSpeed" converter="FloatTextConverter" />
        <field name="selectRandomImage" converter="CheckBoxConverter" />
        <field name="faceNormal" converter="Vector3fConverter" />
        <field name="facingVelocity" converter="CheckBoxConverter" />
        <field name="shape" converter="DataFieldConverter">
            <feature name="componentType" value="shape" />
        </field>
    </data>
    
    
    
</root>

=== huliqing/LuoYing/ly-editor/data/template/LuoYing-RPG/editor/converter/base.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <!--DataConverters-->
    <converter name="SimpleDataConverter" value="name.huliqing.editor.converter.data.SimpleDataConverter" />
    
    <!--FieldConverters-->
    <converter name="UniqueIdConverter" value="name.huliqing.editor.converter.field.UniqueIdConverter" />
    <converter name="TextConverter" value="name.huliqing.editor.converter.field.TextConverter" />
    <converter name="FloatTextConverter" value="name.huliqing.editor.converter.field.FloatTextConverter" />
    <converter name="IntegerTextConverter" value="name.huliqing.editor.converter.field.IntegerTextConverter" />
    <converter name="LongTextConverter" value="name.huliqing.editor.converter.field.LongTextConverter" />
    <converter name="CheckBoxConverter" value="name.huliqing.editor.converter.field.CheckBoxConverter" />
    <converter name="ChoiceConverter" value="name.huliqing.editor.converter.field.ChoiceConverter" />
    <converter name="ColorConverter" value="name.huliqing.editor.converter.field.ColorConverter" />
    <converter name="Vector2fConverter" value="name.huliqing.editor.converter.field.Vector2fConverter" />
    <converter name="Vector3fConverter" value="name.huliqing.editor.converter.field.Vector3fConverter" />
    <converter name="Vector4fConverter" value="name.huliqing.editor.converter.field.Vector4fConverter" />
    <converter name="QuaternionConverter" value="name.huliqing.editor.converter.field.QuaternionConverter" />
    <converter name="FileConverter" value="name.huliqing.editor.converter.field.FileConverter" />
    <converter name="DataFieldConverter" value="name.huliqing.editor.converter.field.DataFieldConverter" />
    <converter name="ListDataFieldConverter" value="name.huliqing.editor.converter.field.ListDataFieldConverter" />
    
    <data name="base" extends="" converter="SimpleDataConverter">
        <field name="tagName" converter="TextConverter">
            <feature name="disabled" value="true" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="id" converter="TextConverter">
            <feature name="disabled" value="true" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="uniqueId" converter="UniqueIdConverter" >
            <feature name="disabled" value="true" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="extends" converter="TextConverter">
            <feature name="disabled" value="true" />
            <feature name="collapsed" value="true" />
        </field>
        <field name="name" converter="TextConverter">
            <feature name="collapsed" value="true" />
        </field>
    </data>
    
</root>

=== huliqing/LuoYing/ly-editor/data/template/LuoYing-RPG/editor/converter/physicsShape.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="physicsShapeBase" extends="base">
    </data>
    
    <data name="physicsShapeBox" extends="physicsShapeBase">
        <field name="extents" converter="Vector3fConverter" />
    </data>
    
    <data name="physicsShapeCapsule" extends="physicsShapeBase">
        <field name="radius" converter="FloatTextConverter" />
        <field name="height" converter="FloatTextConverter" />
        <field name="axis" converter="ChoiceConverter" >
            <feature name="items" value="0,1,2" />
        </field>
    </data>
    
    <data name="physicsShapeDynamicMesh" extends="physicsShapeBase"/>
    
    <data name="physicsShapeSphere" extends="physicsShapeBase">
        <field name="radius" converter="FloatTextConverter" />
    </data>
    
    <data name="physicsShapeStaticCustomMesh" extends="physicsShapeBase">
        <field name="shape" converter="DataFieldConverter">
            <feature name="componentType" value="shape" />
        </field>
    </data>
    
    <data name="physicsShapeStaticMesh" extends="physicsShapeBase"/>
    
    
</root>
