=== huliqing/LuoYing/ly-editor/data/template/LuoYing-RPG/editor/converter/meta.xsd
<?xml version="1.0"?>
<!--
    转换器定义
-->
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://editor.huliqing.name"
           xmlns="http://editor.huliqing.name"
           elementFormDefault="qualified">
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="data" />
                <xs:element ref="converter" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="converter">
        <xs:annotation>
            <xs:documentation>定义一个转换器</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换器名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换器, 格式：name.huliqing.editor.converter.XXXConverter</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="feature">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>feature名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="value" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>feature值</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="data">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>转换tag名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="extends" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>继承自另一个转换器</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="converter" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>关联一个转换器定义</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="features" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>数据转换器的配置，格式："feature1,feature2,feature3"，如果不设置这个参数则使用关联的转换器的默认的配置</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
                <xs:element ref="field" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="field">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="base">
                    <xs:attribute name="name" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>指定要转换的字段名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="displayName" type="xs:string" use="optional" >
                        <xs:annotation>
                            <xs:documentation>指定要显示的字段名称，如果没有指定则直接使用name属性的值作为显示名称</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="converter" type="xs:string" use="required" >
                        <xs:annotation>
                            <xs:documentation>关联一个转换器定义</xs:documentation>
                        </xs:annotation>
                    </xs:attribute>
                </xs:extension>
            </xs:complexContent>
            <xs:sequence>
                <xs:element ref="feature" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="base" >
    </xs:complexType>

</xs:schema>

=== huliqing/LuoYing/ly-editor/data/template/LuoYing-RPG/editor/converter/module.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="moduleBase" extends="base">
        <field name="moduleOrder" converter="IntegerTextConverter" />
        <field name="bindMessageEnabledAttribute" converter="TextConverter" />
    </data>

    <data name="moduleActor" extends="moduleBase">
        <field name="bindDeadAttribute" converter="TextConverter" />
        <field name="bindTargetAttribute" converter="TextConverter" />
        <field name="bindMassAttribute" converter="TextConverter" />
        <field name="bindMovableAttribute" converter="TextConverter" />
        <field name="bindRotatableAttribute" converter="TextConverter" />
        <field name="bindRotatableAttribute" converter="TextConverter" />
        <field name="bindNameAttribute" converter="TextConverter" />
    </data>

    <data name="moduleAction" extends="moduleBase">
        <field name="bindDeadAttribute" converter="TextConverter" />
    </data>

    <data name="moduleChannel" extends="moduleBase">
        <field name="extAnimDir" converter="TextConverter" />
    </data>

    <data name="moduleColor" extends="moduleBase">
        <field name="bindColorAttribute" converter="TextConverter" />
    </data>

    <data name="moduleDrop" extends="moduleBase">
        <field name="bindDeadAttribute" converter="TextConverter" />
    </data>
    
    <data name="moduleItem" extends="moduleBase">
    </data>
    
    <data name="moduleLevel" extends="moduleBase">
        <field name="bindLevelAttribute" converter="TextConverter" />
        <field name="bindXpAttribute" converter="TextConverter" />
        <field name="bindXpNextAttribute" converter="TextConverter" />
        <field name="bindLevelUpEnabledAttribute" converter="TextConverter" />
        <field name="xpLevelEl" converter="TextConverter" />
        <field name="maxLevel" converter="IntegerTextConverter" />
        <field name="effect" converter="TextConverter" />
    </data>

    <data name="moduleLogic" extends="moduleBase">
        <field name="bindEnabledAttribute" converter="TextConverter" />
    </data>

    <data name="modulePhysics" extends="moduleBase">
        <field name="mass" converter="FloatTextConverter" />
        <field name="friction" converter="FloatTextConverter" />
        <field name="restitution" converter="FloatTextConverter" />
        <field name="kinematic" converter="CheckBoxConverter" />
    </data>

    <data name="moduleResist" extends="moduleBase">
    </data>

    <data name="moduleSkill" extends="moduleBase">
        <field name="idleSkillTypes" converter="TextConverter" />
        <field name="waitSkillTypes" converter="TextConverter" />
        <field name="walkSkillTypes" converter="TextConverter" />
        <field name="runSkillTypes" converter="TextConverter" />
        <field name="hurtSkillTypes" converter="TextConverter" />
        <field name="deadSkillTypes" converter="TextConverter" />
        <field name="bindDeadAttribute" converter="TextConverter" />
        <field name="bindHurtAttributes" converter="TextConverter" />
    </data>

    <data name="moduleSkin" extends="moduleBase">
        <field name="bindWeaponSlotAttribute" converter="TextConverter" />
    </data>

    <data name="moduleState" extends="moduleBase">
    </data>

    <data name="moduleTalent" extends="moduleBase">
        <field name="bindLevelAttribute" converter="TextConverter" />
        <field name="bindTalentPointsAttribute" converter="TextConverter" />
        <field name="talentPointsLevelEl" converter="TextConverter" />
    </data>

    <data name="moduleTask" extends="moduleBase">
    </data>

    
</root>

=== huliqing/LuoYing/ly-editor/data/template/LuoYing-RPG/editor/converter/skill.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <converter name="SkillAnimationFieldConverter" value="name.huliqing.editor.converter.field.SkillAnimationFieldConverter" />
    
    <data name="skillBase" extends="base" >
        <field name="icon" converter="FileConverter">
            <feature name="filters" value="Images|*.jpg|*.jpeg|*.png,All Files|*.*" />
        </field>
        <field name="useTime" converter="FloatTextConverter" />
        <field name="types" converter="TextConverter" />
        <field name="overlapTypes" converter="TextConverter" />
        <field name="interruptTypes" converter="TextConverter" />
        <field name="prior" converter="IntegerTextConverter" />
        <field name="cooldown" converter="FloatTextConverter" />
        <field name="weaponStateLimit" converter="TextConverter" />
        <field name="loop" converter="CheckBoxConverter" />
        <field name="sounds" converter="TextConverter" />
        <field name="effects" converter="TextConverter" />
        <field name="boneEffects" converter="TextConverter" />
        <field name="magics" converter="TextConverter" />
        <field name="actorAnims" converter="TextConverter" />
        <field name="checkEl" converter="TextConverter" />
        <field name="level" converter="IntegerTextConverter" />
        <field name="maxLevel" converter="IntegerTextConverter" />
        <field name="levelEl" converter="TextConverter" />
        <field name="levelUpEl" converter="TextConverter" />
        <field name="playCount" converter="IntegerTextConverter" />
        <field name="useAttributes" converter="TextConverter" />
        <field name="bindSpeedAttribute" converter="TextConverter" />
        <field name="bindAvoidInterruptAttribute" converter="TextConverter" />
    </data>
    
    <data name="skillSimpleAnimationBase" extends="skillBase" >
        <field name="animation" converter="SkillAnimationFieldConverter" />
        <field name="channels" converter="TextConverter" />
        <field name="channelLockAll" converter="CheckBoxConverter" />
        <field name="channelLocks" converter="TextConverter" />
        <field name="bindCutTimeEndAttribute" converter="TextConverter" />
        <field name="cutTimeStartMax" converter="FloatTextConverter" />
        <field name="cutTimeEndMax" converter="FloatTextConverter" />
    </data>
    
    <data name="skillWait" extends="skillSimpleAnimationBase"/>
    
    <data name="skillWalkBase" extends="skillSimpleAnimationBase">
        <field name="animSpeed" converter="FloatTextConverter" />
        <field name="baseSpeed" converter="FloatTextConverter" />
    </data>
    <data name="skillWalk" extends="skillWalkBase" />
    <data name="skillRun" extends="skillWalkBase" />
    
    <data name="skillIdle" extends="skillSimpleAnimationBase" />
    
    <data name="skillJump" extends="skillBase" >
        <field name="animStart" converter="SkillAnimationFieldConverter" />
        <field name="animInAir" converter="SkillAnimationFieldConverter" />
        <field name="animEnd" converter="SkillAnimationFieldConverter" />
        <field name="animInAirLoop" converter="ChoiceConverter" >
            <feature name="items" value="Loop,DontLoop,Cycle" />
        </field>
        <field name="useTimeInStart" converter="FloatTextConverter" />
        <field name="useTimeInAir" converter="FloatTextConverter" />
        <field name="useTimeInEnd" converter="FloatTextConverter" />
        <field name="forceApplyTime" converter="FloatTextConverter" />
        <field name="jumpDir" converter="Vector3fConverter" />
        <field name="jumpIntensity" converter="FloatTextConverter" />
        <field name="bindJumpIntensityAttribute" converter="TextConverter" />
    </data>
    
    <data name="skillHurt" extends="skillSimpleAnimationBase" >
        <field name="hurtFace" converter="ChoiceConverter">
            <feature name="items" value="front,back,left,right" />
        </field>
    </data>
    
    <data name="skillReset" extends="skillSimpleAnimationBase" >
        <field name="timePoint" converter="FloatTextConverter" />
    </data>
    
    <data name="skillDefend" extends="skillSimpleAnimationBase">
        <field name="defendDir" converter="ChoiceConverter">
            <feature name="items" value="front,back,left,right" />
        </field>
    </data>
    
    <data name="skillDuck" extends="skillSimpleAnimationBase" >
        <field name="duckDir" converter="ChoiceConverter">
            <feature name="items" value="front,back,left,right" />
        </field>
        <field name="force" converter="TextConverter" />
    </data>
    
    <data name="skillDeadRagdoll" extends="skillSimpleAnimationBase" >
        <field name="useRagdoll" converter="CheckBoxConverter" />
        <field name="forceOnly" converter="CheckBoxConverter" />
        <field name="bones" converter="TextConverter" />
        <field name="bonesHit" converter="TextConverter" />
        <field name="deadAnimPoint" converter="FloatTextConverter" />
        <field name="lastWords" converter="TextConverter" />
    </data>
    
    <data name="skillDead" extends="skillSimpleAnimationBase" >
        <field name="remove" converter="CheckBoxConverter" />
    </data>
    
    <data name="skillHitBase" extends="skillSimpleAnimationBase" >
        <field name="bindTargetAttribute" converter="TextConverter" />
        <field name="hitCheckEl" converter="TextConverter" />
        <field name="hitAttribute" converter="TextConverter" />
        <field name="hitValue" converter="FloatTextConverter" />
        <field name="hitDistance" converter="FloatTextConverter" />
        <field name="hitAngle" converter="FloatTextConverter" />
        <field name="hitEl" converter="TextConverter" />
        <field name="hitStates" converter="TextConverter" />
        <field name="hitMagics" converter="TextConverter" />
    </data>
    
    <data name="skillAttack" extends="skillHitBase" >
        <field name="multHit" converter="CheckBoxConverter" />
        <field name="checkPoint" converter="TextConverter" />
        <field name="defendable" converter="CheckBoxConverter" />
        <field name="defendSkillTypes" converter="TextConverter" />
        <field name="collisionOffset" converter="Vector3fConverter" />
    </data>
    
    <data name="skillShotBase" extends="skillHitBase" >
        <field name="bullets" converter="TextConverter" />
        <field name="shotTimes" converter="TextConverter" />
        <field name="shotOffsets" converter="TextConverter" />
        <field name="shotSpeed" converter="FloatTextConverter" />
        <field name="multHit" converter="CheckBoxConverter" />
        <field name="multTarget" converter="CheckBoxConverter" />
        <field name="shotTargetType" converter="ChoiceConverter">
            <feature name="items" value="origin,center,bound" />
        </field>
    </data>
    
    <data name="skillShot" extends="skillShotBase" />
    
    <data name="skillShotBow" extends="skillShotBase">
        <field name="weaponAnim" converter="TextConverter" />
        <field name="timeBulletTake" converter="FloatTextConverter" />
        <field name="timeBulletPull" converter="FloatTextConverter" />
        <field name="arrow" converter="FileConverter">
            <feature name="filters" value="Model Files|*.j3o,All Files|*.*" />
        </field>
        <field name="animationShotDown" converter="TextConverter" />
        <field name="animationShotUp" converter="TextConverter" />
        <field name="arrowBindBone" converter="TextConverter" />
        <field name="shotDownOffset" converter="Vector3fConverter" />
        <field name="shotUpOffset" converter="Vector3fConverter" />
    </data>
    
    <data name="skillBack" extends="skillSimpleAnimationBase" >
        <field name="backPoint" converter="FloatTextConverter" />
    </data>
    
    <data name="skillSummon" extends="skillSimpleAnimationBase">
        <field name="summonActorId" converter="TextConverter" />
        <field name="copyAttributesFromSource" converter="TextConverter" />
        <field name="linkAttributesToSource" converter="TextConverter" />
        <field name="summonOffset" converter="Vector3fConverter" />
        <field name="summonPoint" converter="FloatTextConverter" />
        <field name="summonTime" converter="FloatTextConverter" />
    </data>
    
    <data name="skillSkin" extends="skillSimpleAnimationBase">
        <field name="hangTimePoint" converter="FloatTextConverter" />
    </data>

</root>

=== huliqing/LuoYing/ly-editor/data/template/LuoYing-RPG/editor/converter/attribute.xml
<?xml version="1.0" encoding="UTF-8"?>

<root
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://editor.huliqing.name'
    xsi:schemaLocation='http://editor.huliqing.name meta.xsd'>
    
    <data name="attributeBoolean" extends="base">
        <field name="value" converter="CheckBoxConverter" />
    </data>
    
    <data name="attributeFloat" extends="base">
        <field name="value" converter="FloatTextConverter" />
    </data>
    
    <data name="attributeGroup" extends="base">
<!--        <field name="attributes" converter="ListDataFieldConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.AttributeData" />
            <feature name="componentType" value="attribute" />
            <feature name="collapsed" value="false" />
        </field>-->
        <field name="attributes" converter="TextConverter">
        </field>
    </data>
    
    <data name="attributeInteger" extends="base">
        <field name="value" converter="IntegerTextConverter" />
    </data>
    
    <data name="attributeLevelFloat" extends="base">
        <field name="value" converter="FloatTextConverter" />
        <field name="level" converter="IntegerTextConverter" />
        <field name="levelEl" converter="DataFieldConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.ElData" />
            <feature name="componentType" value="el" />
        </field>
    </data>
    
    <data name="attributeLevelInteger" extends="base">
        <field name="value" converter="IntegerTextConverter" />
        <field name="level" converter="IntegerTextConverter" />
        <field name="levelEl" converter="DataFieldConverter">
            <feature name="dataType" value="name.huliqing.luoying.data.ElData" />
            <feature name="componentType" value="el" />
        </field>
    </data>
    
    <data name="attributeLimitInteger" extends="base">
        <field name="value" converter="IntegerTextConverter" />
        <field name="minValue" converter="IntegerTextConverter" />
        <field name="maxValue" converter="IntegerTextConverter" />
        <field name="bindMinLimitAttribute" converter="TextConverter"/>
        <field name="bindMaxLimitAttribute" converter="TextConverter"/>
    </data>
    
    <data name="attributeLong" extends="base">
        <field name="value" converter="LongTextConverter" />
    </data>
    
    <data name="attributeRelateBoolean" extends="base">
        <field name="value" converter="CheckBoxConverter" />
        <field name="refVars" converter="TextConverter" />
        <field name="valueEl" converter="TextConverter" />
    </data>
    
    <data name="attributeString" extends="base">
        <field name="value" converter="TextConverter" />
    </data>
    
    <data name="attributeStringList" extends="base">
        <field name="value" converter="TextConverter" />
        <field name="duplication" converter="CheckBoxConverter" />
    </data>
    
    <data name="attributeVector2f" extends="base">
        <field name="value" converter="Vector2fConverter" />
    </data>
    
    <data name="attributeVector3f" extends="base">
        <field name="value" converter="Vector3fConverter" />
    </data>
    
    <data name="attributeVector4f" extends="base">
        <field name="value" converter="Vector4fConverter" />
    </data>

    
</root>
