=== huliqing/LuoYing/ly-kernel/src/data/object/meta/emitter.xsd
<?xml version="1.0"?>
<!--
xs:string
xs:decimal
xs:integer
xs:boolean
xs:date
xs:time
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://fighter.huliqing.name"
           xmlns="http://fighter.huliqing.name"
           elementFormDefault="qualified" >
    
    <xs:include schemaLocation="base.xsd" />
    
    <xs:element name="root">
        <xs:complexType>
            <xs:all>
                <xs:element ref="emitter" />
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="emitter" type="emitter" />
    
    <xs:complexType name="emitter">
        <xs:complexContent>
            <xs:extension base="base">
                <xs:attribute name="numParticles" use="required" >
                    <xs:annotation>
                        <xs:documentation>e.g. "10"</xs:documentation>
                    </xs:annotation>
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="1"  />
                            <xs:maxInclusive value="30" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="startColor" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>RGBA, e.g. "1, 1, 0, 1" </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="endColor" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>RGBA, e.g. "1, 0, 0, 1" </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="startSize" type="xs:decimal" use="required">
                    <xs:annotation>
                        <xs:documentation>e.g. "0.2"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="endSize" type="xs:decimal" use="required">
                    <xs:annotation>
                        <xs:documentation>e.g. "1.0" </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="highLife" type="xs:decimal" use="required">
                    <xs:annotation>
                        <xs:documentation>e.g. "1.0"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="lowLife" type="xs:decimal" use="required">
                    <xs:annotation>
                        <xs:documentation>e.g. "0.2"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="texture" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>e.g. "Textures/tex/effect/flash.png"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="imagesX" type="xs:integer" use="required">
                    <xs:annotation>
                        <xs:documentation>e.g. "2"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="imagesY" type="xs:integer" use="required">
                    <xs:annotation>
                        <xs:documentation>e.g. "2" </xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="gravity" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>e.g. "0, 0, 0"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="initialVelocity" type="xs:string" use="required">
                    <xs:annotation>
                        <xs:documentation>e.g. "0,0,0"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="velocityVariation" type="xs:decimal" use="required">
                    <xs:annotation>
                        <xs:documentation>e.g. "0.0"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="particlesPerSec" type="xs:integer" use="optional">
                    <xs:annotation>
                        <xs:documentation>e.g. "10.0"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="randomAngle" use="optional" type="bool">
                    <xs:annotation>
                        <xs:documentation>e.g. "0" or "1"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="rotateSpeed" type="xs:decimal" use="optional">
                    <xs:annotation>
                        <xs:documentation>e.g. "1.0"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="selectRandomImage" type="bool" use="optional" default="0" >
                    <xs:annotation>
                        <xs:documentation>e.g. "0" or "1"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="faceNormal" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>e.g. "1, 1, 1"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="facingVelocity" type="bool" use="optional">
                    <xs:annotation>
                        <xs:documentation>e.g. "0" or "1"</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
                <xs:attribute name="shape" type="xs:string" use="optional">
                    <xs:annotation>
                        <xs:documentation>关联一个emitterShape</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    

    
    
</xs:schema>

=== huliqing/LuoYing/ly-kernel/src/resources/object/emitter.xml
<?xml version="1.0" encoding="UTF-8"?>

<root 
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://luoying.huliqing.name'
    xsi:schemaLocation='http://luoying.huliqing.name meta/emitter.xsd' >
    
    <!-- ========== Test Start ========== -->
    <emitter id="emitterTest" numParticles="8" startColor="1,1,1,0.5" endColor="1,1,1,0.1" startSize="2" endSize="2" highLife="1.5" 
             lowLife="1" texture="Textures/effect/flame2.png" imagesX="8" imagesY="1" initialVelocity="0,0.5,0" velocityVariation="0.1"
             particlesPerSec="3" shape="" selectRandomImage="0" randomAngle="0" rotateSpeed="0" />
    <!-- ========== Test End ========== -->
    
    <!-- =================================================================== -->
    <!--通用：材质碰撞-->
    <!-- =================================================================== -->
    <!--火花-->
    <emitter id="emitterCollisionMM1" numParticles="10" 
             startColor="1, 0.8, 0.36, 1" endColor="0.4, 0.22, 0.12, 0" 
             startSize="1" endSize="0.5" highLife="0.5" lowLife="0.3" shape=""
             texture="Textures/effect/spark.png" imagesX="1" imagesY="1" 
             facingVelocity="1" particlesPerSec="0" gravity="0,0,-100" initialVelocity="0, 0, -30" velocityVariation="0.5" />
    <!--闪光-->
    <emitter id="emitterCollisionMM2"  numParticles="1" 
             startColor="1, 0.8, 0.36, 5" endColor="0.4, 0.22, 0.12, 0" 
             startSize="1" endSize="1" 
             shape="" highLife="0.1" lowLife="0.1" 
             texture="Textures/effect/flash.png" imagesX="2" imagesY="2" 
             particlesPerSec="0" gravity="0,0,0" initialVelocity="0,0,0" velocityVariation="1" />
    
    <!-- =================================================================== -->
    <!--通用：火焰爆炸-->
    <!-- =================================================================== -->
    <!--火焰-->
    <emitter id="emitterFlame" name="flame" numParticles="5" 
             startColor="1,0.4,0.05,1" endColor="0.4, 0.22, 0.12, 0" startSize="1.3" 
             endSize="2" highLife="0.5" lowLife="0.4" texture="Textures/effect/flame.jpg" 
             imagesX="2" imagesY="2" selectRandomImage="1" shape="esFlameShape" 
             particlesPerSec="0" gravity="0, -5, 0" initialVelocity="0,7,0" velocityVariation="1" />
    <!--闪光-->
    <emitter id="emitterFlash" name="flash" numParticles="5" 
             selectRandomImage="1" startColor="1,0.8,0.36,1" 
             endColor="1,0.8,0.36,0" startSize="0.1" endSize="3.0" 
             shape="esFlashShape" highLife="0.2" lowLife="0.2" 
             texture="Textures/effect/flash.png" imagesX="2" imagesY="2" 
             particlesPerSec="0" gravity="0,0,0" initialVelocity="0,5,0" velocityVariation="1" />
    <!--火花-->
    <emitter id="emitterSpark" name="spark" numParticles="5" 
             startColor="1, 0.8, 0.36, 1" endColor="1, 0.8, 0.36, 0" 
             startSize="1" endSize="0.5" highLife="1.5" lowLife="1.1" 
             texture="Textures/effect/spark.png" imagesX="1" imagesY="1" 
             facingVelocity="1" particlesPerSec="0" gravity="0,0,0" 
             initialVelocity="0, 10, 0" velocityVariation="1" />
    <!--向四周发散的冲击波-->
    <emitter id="emitterShockwave" name="shockwave" 
             numParticles="1" startColor="0.48, 0.17, 0.01, 0.8" endColor="0.48, 0.17, 0.01, 0" 
             startSize="0" endSize="7" highLife="0.5" lowLife="0.5" 
             texture="Textures/effect/shockwave.png" imagesX="1" imagesY="1" 
             faceNormal="0,1,0" particlesPerSec="0" gravity="0,0,0" 
             initialVelocity="0,0,0" velocityVariation="0" />
    
    <!-- =================================================================== -->
    <!--通用：雪花爆炸-->
    <!-- =================================================================== -->
    <emitter id="emitterSnowFlame" numParticles="5" 
             startColor="1,1,1,1" endColor="0.3, 0.3, 1, 0" startSize="1.3" 
             endSize="2" highLife="0.5" lowLife="0.4" texture="Textures/effect/flame.jpg" 
             imagesX="2" imagesY="2" selectRandomImage="0" shape="esFlameShape" 
             particlesPerSec="0" gravity="0, -5, 0" initialVelocity="0,7,0" velocityVariation="1" />
    <emitter id="emitterSnowSpark" numParticles="5" 
             startColor="0.3,0.3,1,1" endColor="0.3,0.3,1,0" 
             startSize="1" endSize="0.5" highLife="1.5" lowLife="1.1" 
             texture="Textures/effect/spark.png" imagesX="1" imagesY="1" 
             facingVelocity="1" particlesPerSec="0" gravity="0,0,0" 
             initialVelocity="0, 10, 0" velocityVariation="1" />
    
    <!-- =================================================================== -->
    <!--冰冻：冰冻效果的冰花爆炸，带碎片块和冰雾-->
    <!-- =================================================================== -->
    <emitter id="emitterIceDebris" numParticles="15" particlesPerSec="0" 
             startColor="1,1,1,1" endColor="0.5,0.5,1,0" 
             startSize="0.15" endSize="0.03" highLife="3" lowLife="2" 
             texture="Textures/effect/debris.jpg" imagesX="3" imagesY="3" 
             facingVelocity="0" gravity="0,10,0"
             initialVelocity="0, 10, 0" velocityVariation="0.4" /> 
    <emitter id="emitterIceSmoke" numParticles="10" 
             startColor="1,1,1,1" endColor="0.3, 0.3, 1, 0" startSize="1" 
             endSize="3" highLife="2" lowLife="1" texture="Textures/effect/flame.jpg" 
             imagesX="2" imagesY="2" selectRandomImage="0" shape="esFlameShape" rotateSpeed="1"
             particlesPerSec="0" gravity="0,8,0" initialVelocity="0,5,0" velocityVariation="0.5" />
    
    <!-- ====================================================================-->
    <!--火塔尾焰-->
    <!-- ====================================================================-->

    <!--烟雾，火光，火球发射过程-->
    <emitter id="emitterSmoketrail" name="smoketrail" 
             numParticles="20" particlesPerSec="20" 
             startColor="1,1,0,1" endColor="1,0,0,1" startSize="1.5" endSize="0.75" 
             highLife="0.25" lowLife="0.25" 
             texture="Textures/effect/smoketrail.png" imagesX="1" imagesY="3"
             facingVelocity="1" initialVelocity="0,0,1" velocityVariation="0" gravity="0,0,0"
    />
    
    <!--=====================================================================-->
    <!--石塔:石块和尾烟-->
    <!--=====================================================================-->
    
    <!--石块-->
    <emitter id="emitterTowerRock" numParticles="1" randomAngle="1" selectRandomImage="1"
             startColor="2,2,2,2" endColor="2,2,2,2" 
             startSize="0.5" endSize="0.5" highLife="15" lowLife="15" 
             texture="Textures/effect/debris_alpha.png" imagesX="3" imagesY="3" gravity="0,0,0"
             initialVelocity="" velocityVariation="" />
    <!--烟雾-->
    <emitter id="emitterTowerSmoke"
             numParticles="20" particlesPerSec="20" 
             startColor="0.4,0.4,0.4,1" endColor="0.9,0.9,0.9,0.1" startSize="1.2" endSize="0.1" 
             highLife="1.5" lowLife="0.1" 
             texture="Textures/effect/smoke15.png" imagesX="15" imagesY="1"
             facingVelocity="0" initialVelocity="0,0.1,0" velocityVariation="0.5" gravity="0,-2,0"
            />

    <!--=====================================================================-->
    <!--雪花拖尾-->
    <!--=====================================================================-->
    
    <!--雪花拖尾-->
    <emitter id="emitterSnowTrail" numParticles="20" particlesPerSec="10" 
             startColor="1,1,1,1" endColor="0.3,0.3,1,0.5" startSize="1.5" endSize="0.5" 
             highLife="0.25" lowLife="0.25" 
             texture="Textures/effect/smoketrail.png" imagesX="1" imagesY="3"
             facingVelocity="1" initialVelocity="0,0,1" velocityVariation="0" gravity="0,0,0"
    />
    
    <!--雪花粒-->
    <emitter id="emitterSnowFlake" numParticles="30" particlesPerSec="20" 
             startColor="1,1,1,1" endColor="0.3,0.3,1,0.1" startSize="0.5" endSize="0.1" 
             highLife="0.5" lowLife="0.3" 
             texture="Textures/effect/flame.jpg" imagesX="2" imagesY="2"
             facingVelocity="0" initialVelocity="0,0,-5" velocityVariation="0.2" gravity="0,0,0"
    />
    
    <!--=====================================================================-->
    <!--补红补蓝-->
    <!--=====================================================================-->
    <emitter id="emitterRandomFire" numParticles="5" startColor="1, 1, 0, 0.5" endColor="1, 0, 0, 1" shape="esRandomFire"
             startSize="1" endSize="0.3" highLife="0.3" lowLife="0.3" texture="Textures/effect/spark.png" 
             imagesX="1" imagesY="1" gravity="0,0,0" velocityVariation="0" initialVelocity="0,3,0" facingVelocity="1" />

    <!--=====================================================================-->
    <!--级效果粒子-->
    <!--=====================================================================-->

    <!--用于升级效果，在一个圆柱的范围内随机产生粒子-->
    <emitter id="emitterLevelUp" name="emitterLevelUp" numParticles="15" 
             startColor="1, 1, 1, 0.5" endColor="1, 1, 1, 0.5" shape="esCylinder"
             startSize="4" endSize="2" highLife="0.8" lowLife="0.4" texture="Textures/effect/spark.png" 
             imagesX="1" imagesY="1" gravity="0,0,0" velocityVariation="0" initialVelocity="0,1,0" 
             particlesPerSec="15" facingVelocity="1"/>
    
    <!--=====================================================================-->
    <!--剑火花-->
    <!--=====================================================================-->
    <emitter id="emitterSwordSpark" name="spark" numParticles="10" 
             startColor="1, 0.8, 0.36, 1" endColor="1, 0.8, 0.36, 1" 
             startSize="1" endSize="0.3" highLife="0.6" lowLife="0.2" 
             texture="Textures/effect/spark.png" imagesX="1" imagesY="1" 
             facingVelocity="1" particlesPerSec="0" gravity="0,0,0" 
             shape="esSwordSpark"
